export const MODULOS = {
  GESTION_SEGURIDAD: 'GSEG',
  GESTION_ADMINISTRACION: 'GADM',
  GESTION_ROLES: 'GROL',
  GESTION_MODULOS: 'GMOD',
  GESTION_PERMISOS: 'GPRM',
  GESTION_PARAMETROS: 'GPAR',
  GESTION_USUARIOS: 'GUSU',
  GESTION_TIPO_ACTIVIDAD: 'GTIPACT',
  GESTION_FORMATO_ACTIVIDAD: 'GFORACT',
  GESTION_REGISTRO_ACTIVIDAD: 'GREGACT',
};
